### ISSUE TITLE
Quantile cross-spectral density not supporting unequal length MTS

### ISSUE THREAD

**Issue by Victordmz** [cran/mlmts#1]
The function in R/dis_qcd.R calls `check_mts_rows`, enforcing an equal length MTS. However, the [paper that introduces this density](https://www.sciencedirect.com/science/article/pii/S0957417421010630) mentions in the conclusions section that "it can be applied to cluster series of unequal length".

What is the reason that the call to `check_mts_rows` is made? Thank you!

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
